# SPDX-License-Identifier: LGPL-2.1-or-later
#pyright: standard, reportUnusedImport=error, reportMissingImports=information
from typing import Protocol, Self, Any, Literal, Optional, overload
from Part import Edge, Face, Vertex, Shape 
import FreeCADGui as Gui 


class Vector(Protocol):
    x: float
    y: float
    z: float
    Length: float 

    def cross(self, vector2) -> Self: ...
    def distanceToLine(self, base, dir) -> float: ...
    def distanceToLineSegment(self, point1, point2) -> Self: ...
#    distanceToPlane(self, base, normal, /)
#    distanceToPlane(base: 'Vector', normal: 'Vector', /) -> float
#    
#    Returns the distance between this vector and a plane defined by a
#    base point represented by `base` and a normal defined by `normal`.
#    
#    base : Base.Vector
#    normal : Base.Vector
#    distanceToPoint(self, point2, /)
#    distanceToPoint(point2: 'Vector', /) -> float
#    
#    Returns the distance to another point represented by `point2`.
#    .
#    point : Base.Vector
    def dot(self, vector2: Self) -> Self: ...
    def __mul__(self, vector2: Self | int | float) -> Self: ...
    def __rmul__(self, vector2: Self | int | float) -> Self: ...
#    dot(vector2: 'Vector', /) -> float
#    
#    Returns the scalar product (dot product) between this vector and `vector2`.
#    
#    vector2 : Base.Vector
#    getAngle(self, vector2, /)
#    getAngle(vector2: 'Vector', /) -> float
#    
#    Returns the angle in radians between this vector and `vector2`.
#    
#    vector2 : Base.Vector
#    isEqual(self, vector2, tol=0, /)
#    isEqual(vector2: 'Vector', tol: float=0, /) -> bool
#    
#    Checks if the distance between the points represented by this vector
#    and `vector2` is less or equal to the given tolerance.
#    
#    vector2 : Base.Vector
#    tol : float
#    isNormal(self, vector2, tol=0, /)
#    isNormal(vector2: 'Vector', tol: float=0, /) -> bool
#    
#    Checks if this vector and `vector2` are
#    normal less or equal to the given tolerance.
#    
#    vector2 : Base.Vector
#    tol : float
#    isOnLineSegment(self, vector1, vector2, /)
#    isOnLineSegment(vector1: 'Vector', vector2: 'Vector', /) -> bool
#    
#    Checks if this vector is on the line segment generated by `vector1` and `vector2`.
#    
#    vector1 : Base.Vector
#    vector2 : Base.Vector
#    isParallel(self, vector2, tol=0, /)
#    isParallel(vector2: 'Vector', tol: float=0, /) -> bool
#    
#    Checks if this vector and `vector2` are
#    parallel less or equal to the given tolerance.
#    
#    vector2 : Base.Vector
#    tol : float
#    multiply(self, factor, /)
#    multiply(factor: float, /) -> 'Vector'
#    
#    Multiplies in-place each component of this vector by a single factor.
#    Equivalent to scale(factor, factor, factor).
#    
#    factor : float
#    negative(self, /)
#    negative() -> 'Vector'
#    
#    Returns the negative (opposite) of this vector.
#    normalize(self, /)
    def normalize(self) -> Self: ...
#    
#    Normalizes in-place this vector to the length of 1.0.
#    projectToLine(self, point, dir, /)
#    projectToLine(point: 'Vector', dir: 'Vector', /) -> 'Vector'
#    
#    Projects `point` on a line that goes through the origin with the direction `dir`.
#    The result is the vector from `point` to the projected point.
#    The operation is equivalent to dir_n.cross(dir_n.cross(point)), where `dir_n` is
#    the vector `dir` normalized.
#    The method modifies this vector instance according to result and does not
#    depend on the vector itself.
#    
#    point : Base.Vector
#    dir : Base.Vector
#    projectToPlane(self, base, normal, /)
#    projectToPlane(base: 'Vector', normal: 'Vector', /) -> 'Vector'
#    
#    Projects in-place this vector on a plane defined by a base point
#    represented by `base` and a normal defined by `normal`.
#    
#    base : Base.Vector
#    normal : Base.Vector
#    scale(self, x, y, z, /)
#    scale(x: float, y: float, z: float, /) -> 'Vector'
#    
#    Scales in-place this vector by the given factor in each component.
#    
#    x : float
#        x-component factor scale.
#    y : float
#        y-component factor scale.
#    z : float
#        z-component factor scale.
    def add(self, vector2: Self) -> Self: ...
    def __add__(self, vector2:  Self) -> Self: ...
    def sub(self, vector2: Self) -> Self: ...
    def __sub__(self, vector2:  Self) -> Self: ...
 
class GeomSurface(Protocol):
    def parameter(self, vec: Vector) -> float | tuple[float, float]:
        "Returns the parameter on the curve of the nearest orthogonal projection of the point."
        ...

class Compound(Protocol):
    def getChildShapes(self, topoType: Literal["Solid", "Shell", "Edge", "Wire", "Vertex"]) -> list['ShapeLike']: ...

class ShapeLike(Protocol):
    @property
    def Edges(self) -> list[Edge]: ...
    @property
    def Faces(self) -> list[Face]: ...
    @property
    def Vertexes(self) -> list[Vertex]: ...
    @property
    def ParameterRange(self) -> tuple[float, float]: ...
    @property
    def Wires(self) -> list[Self]: ...
    def makeFillet(self, radius: float, edges: list[Edge]) -> Self: ...
    def extrude(self, direction: Vector) -> Self: ...
    def defeaturing(self, shapes: list[Self]) -> Self: ...
    def makeOffsetShape(self, offset: float, tollerance: float, inter: bool, selfinter: bool, offsetmode: int, join: int, fill: bool) -> Self: ...
    def generalFuse(self, objsToCutWith: list[Self]) -> tuple[Compound, list[list[Self]]]: ...
    def fuse(self, objsToAdd: list[Self]) -> Self: ...
    def check(self) -> bool: ...
    def hashCode(self) -> int: ...
    def normalAt(self, u: float, v: float) -> Vector: ...
    def valueAt(self, u: float) -> Vector: ...
    def add(self, face: Self) -> None:
        "Adds face to shell"
        ...
    @property
    def Surface(self) -> GeomSurface:
        "Returns the geometric surface of the face"
        ...
    @property    
    def FirstParameter(self) -> float: ...
    @property    
    def LastParameter(self) -> float: ...
    def firstVertex(self) -> Self: ...
    def lastVertex(self) -> Self: ...
    @property
    def Point(self) -> Vector: ...

    @overload
    def discretize(self, Number: int, First: Optional[float]=None, Last: Optional[float]=None) -> list[Vector]:...
    @overload
    def discretize(self, QuasiNumber: int, *, First: Optional[float]=None, Last: Optional[float]=None) -> list[Vector]:...
    @overload
    def discretize(self, Distance: float, *, First: Optional[float]=None, Last: Optional[float]=None) -> list[Vector]:...
    @overload
    def discretize(self, Deflection: float, *, First: Optional[float]=None, Last: Optional[float]=None) -> list[Vector]:...
    @overload
    def discretize(self, QuasiDeflection: float, *, First: Optional[float]=None, Last: Optional[float]=None) -> list[Vector]:...
    @overload
    def discretize(self, Angular: float, Curvature: float, Minimum: int=2, *, First: Optional[float]=None, Last: Optional[float]=None) -> list[Vector]:...

    def distToShape(self, shape: Self, tol: float=1e-07) -> tuple[float, list[tuple[Vector, Vector]], list[tuple]]: ...
    def isSeam(self, face: Self) -> bool: ...

class FeatureLike(Protocol):
    Proxy: Any
    Type: str
    BaseFeature: Self
    Shape: Shape
    ViewObject: Gui.ViewProviderDocumentObject
    Visibility: bool
    def check(self) -> bool: ...
    def addProperty(self, type: str, name: str, section: str, description: str) -> None: ...
    def getSubObject(self, name: str) -> ShapeLike: ...

class BodyLike(Protocol):
    Tip: FeatureLike
    def addObject(self, feature: FeatureLike) -> None: ...

class FeatureProxyLike(Protocol):
    def __init__(self, obj: Any) -> None: ...
    @classmethod
    def getFeatureName(cls) -> str: ...
    def add_properties(self, obj) -> None: ...
    def execute(self, obj) -> None: ...
    def onChanged(self, obj, prop) -> None: ...
    def __getstate__(self) -> dict[str, str | Any]: ...
    def __setstate__(self, state) -> None: ...

class VPLike(Protocol):
    def __init__(self, vobj): ...
    def attach(self, vobj): ...
    def updateData(self, obj, prop): ...
    def getDisplayModes(self, vobj) -> list[str]: ...
    def getDefaultDisplayMode(self) -> str: ...
    def setDisplayMode(self, mode): ...
    def onChanged(self, vobj, prop): ...
    def getIcon(self) -> str: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...

